[project]
name = "mcp-lifecycle"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.13.0",
    "requests>=2.32.4",
]
