[project]
name = "01-agent-mcp-http"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.13.1",
    "openai-agents>=0.2.10",
    "python-dotenv>=1.1.1",
]
