[project]
name = "cli-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp>=1.12.0",
    "openai-agents>=0.2.2",
    "prompt-toolkit>=3.0.51",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
